apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: ecommerce-prod
type: Opaque
data:
  # Base64 encoded values
  # username: postgres -> cG9zdGdyZXM=
  # password: password -> cGFzc3dvcmQ=
  username: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=
